build:
  version: "1.0"

cards:
  message: "Welcome to WahidBank cards related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@wahidbank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345