build:
  version: "1.0"

loans:
  message: "Welcome to WahidBank loans related production APIs "
  contactDetails:
    name: "Abdul - Prod Lead"
    email: "abdul@wahidbank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345