spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to WahidBank accounts related prod APIs "
  contactDetails:
    name: "Hales  - Prod Lead"
    email: "Hales@wahidbank.com"
  onCallSupport:
    - (453) 392-3765
    - (236) 203-8371