spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "1.0"

cards:
  message: "Welcome to WahidBank cards related qa APIs "
  contactDetails:
    name: "Jahangir - QA Lead"
    email: "jahangir@wahidbank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345